### ISSUE TITLE
rename blobs to match norsk-config/ validators

### ISSUE THREAD

**Issue by mingxiao** [aemengo/bosh-runc-cpi-release#1]
Currently when this release is added into our (Ops Manager) configuration file:

```
- repo: git@github.com:aemengo/bosh-runc-cpi-release.git
  scan_root_folder: false
  dependencies:
  - path: src/github.com/aemengo/bosh-runc-cpi
  - path: src/github.com/aemengo/blt
  - path: src/github.com/aemengo/blt/vendor/github.com/fatih/color
  - path: src/github.com/aemengo/vpnkit-manager
```

We see the follow error when validating that release:
```
============================   Checking against blobs configurations   ============================

❌ runc-cpi-darwin has no blobs.yml configuration or interpolated values are not matched
❌ runc-cpi-linux has no blobs.yml configuration or interpolated values are not matched
```

Can we rename those blobs such that they match the patterns that norsk recognizes?
https://github.com/pivotal-cf/norsk-config/blob/master/blobs.yml#L985

@vyadav of #rd-osl-tooling also has context
